### ISSUE TITLE
关于taro版本的问题

### ISSUE THREAD

**Issue by licorace** [bigmeow/taro-platform#3]
您好，请问一下，您在readme中介绍说，Taro 版本号  需>= 3.6.0，但是 taro最新的不是3.5.12么，不知道您是笔误还是啥😂？

**Comment by bigmeow** [comment]
非笔误，正式版没发，测试版当时已经发了。截止到现在， 正式版也已经发了。
我在 `taro3.6` 版本中为了支持使用 `axios`， 开发了2种方案， 这是其中一个方案，另外一个方案是 `@tarojs/plugin-http`
